title: "TiRKiO"
description: "A minimal Jekyll theme styled with PicoCSS."
baseurl: "" # Leave empty for GitHub Pages root
url: "https://www.tirkio.com"
theme: jekyll-theme-picocss
github_username: "tirkio"
